name: Create Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build_and_release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build the binaries
        run: make release

      - name: Create archives dynamically
        run: |
          mkdir -p build
          name="${GITHUB_REPOSITORY#*/}"

          for dir in build/*; do
            if [ -d "$dir" ]; then
              base_name=$(basename "$dir")
              temp_dir="$(mktemp -d)"
              folder_name="${name}-${base_name}"

              mkdir -p "$temp_dir/$folder_name"

              if [[ "$base_name" == *windows* ]]; then
                binary="zdu.exe"
                archive_name="build/${folder_name}.zip"
                if [ -f "$dir/$binary" ]; then
                  cp "$dir/$binary" "$temp_dir/$folder_name/"
                  cp LICENSE README.md "$temp_dir/$folder_name/"
                  (cd "$temp_dir" && zip -r "$archive_name" "$folder_name")
                  echo "Created Windows archive: $archive_name"
                else
                  echo "Skipping $dir: $binary not found"
                fi
              else
                binary="zdu"
                archive_name="build/${folder_name}.tar.gz"
                if [ -f "$dir/$binary" ]; then
                  cp "$dir/$binary" "$temp_dir/$folder_name/"
                  cp LICENSE README.md "$temp_dir/$folder_name/"
                  tar -czf "$archive_name" -C "$temp_dir" "$folder_name"
                  echo "Created archive: $archive_name"
                else
                  echo "Skipping $dir: $binary not found"
                fi
              fi

              rm -rf "$temp_dir"
            fi
          done

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          archives=""
          for f in build/*.{tar.gz,zip}; do
            if [ -f "$f" ]; then
              archives="$archives $f"
            fi
          done

          if [ -n "$archives" ]; then
            gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              $archives
            echo "Release created with archives: $archives"
          else
            echo "No archives to upload"
          fi
